import React from "react";
import Footer from "../components/_App/Footer";

const PrivacyPolicy = () => {
  return (
    <React.Fragment>
      <div
        className="privacy-area ptb-100"
        style={{ backgroundColor: "#ebebeb" }}
      >
        <div className="container">
          <h2 className="privecyPolicy-header">
            Last updated: October 14, 2020
          </h2>
          <h6 className="privecyPolicy-content">
            This Privacy Policy describes Our policies and procedures on the
            collection, use and disclosure of Your information when You use the
            Service and tells You about Your privacy rights and how the law
            protects You.
            <br />
            <br />
            We use Your Personal data to provide and improve the Service. By
            using the Service, You agree to the collection and use of
            information in accordance with this Privacy Policy.
            <br />
            This Privacy Policy has been created with the help of the{" "}
            <a
              href="https://www.termsfeed.com/privacy-policy-generator/"
              className="privecyPolicy-link"
            >
              Privacy Policy Generator
            </a>
            .
          </h6>

          <h2 className="privecyPolicy-header">
            Interpretation and Definitions
          </h2>
          <h4 className="privecyPolicy-subHeader">Interpretation</h4>
          <h6 className="privecyPolicy-content">
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions.
            <br />
            The following definitions shall have the same meaning regardless of
            whether they appear in singular or in plural.
          </h6>
          <h3 className="privecyPolicy-subHeader">Definitions</h3>
          <h6 className="privecyPolicy-content">
            For the purposes of this Privacy Policy:
          </h6>
          <ul className="privecyPolicy-list">
            <li>
              Account means a unique account created for You to access our
              Service or parts of our Service.
            </li>
            <li>
              Company (referred to as either "the Company", "We", "Us" or "Our"
              in this Agreement) refers to BIOMARKERZ LTD, 1 eli cohen.
            </li>
            <li>
              Cookies are small files that are placed on Your computer, mobile
              device or any other device by a website, containing the details of
              Your browsing history on that website among its many uses.
            </li>
            <li>Country refers to: Israel</li>
            <li>
              Device means any device that can access the Service such as a
              computer, a cellphone or a digital tablet.
            </li>
            <li>
              Personal Data is any information that relates to an identified or
              identifiable individual.
            </li>
            <li>Service refers to the Website.</li>
            <li>
              Service Provider means any natural or legal person who processes
              the data on behalf of the Company. It refers to third-party
              companies or individuals employed by the Company to facilitate the
              Service, to provide the Service on behalf of the Company, to
              perform services related to the Service or to assist the Company
              in analyzing how the Service is used.
            </li>
            <li>
              Third-party Social Media Service refers to any website or any
              social network website through which a User can log in or create
              an account to use the Service.
            </li>
            <li>
              Usage Data refers to data collected automatically, either
              generated by the use of the Service or from the Service
              infrastructure itself (for example, the duration of a page visit).
            </li>
            <li>
              Website refers to BIOMARKERZ, accessible from{" "}
              <a
                href="https://www.termsfeed.com/privacy-policy-generator/"
                className="privecyPolicy-link"
              >
                https://www.biomarkerz.com
              </a>
            </li>
            <li>
              You means the individual accessing or using the Service, or the
              company, or other legal entity on behalf of which such individual
              is accessing or using the Service, as applicable.
            </li>
          </ul>

          <h3 className="privecyPolicy-subHeader">
            Collecting and Using Your Personal Data
          </h3>
          <h3 className="privecyPolicy-subHeader">Types of Data Collected</h3>
          <h3 className="privecyPolicy-subHeader">Personal Data</h3>
          <h6>
            While using Our Service, We may ask You to provide Us with certain
            personally identifiable information that can be used to contact or
            identify You. <br />
            Personally identifiable information may include, but is not limited
            to:
          </h6>
          <ul className="privecyPolicy-list">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Usage Data</li>
          </ul>

          <h3>Usage Data</h3>
          <h6>
            Usage Data is collected automatically when using the Service. Usage
            Data may include information such as Your Device's Internet Protocol
            address (e.g. IP address), browser type, browser version, the pages
            of our Service that You visit, the time and date of Your visit, the
            time spent on those pages, unique device identifiers and other
            diagnostic data.
            <br />
            When You access the Service by or through a mobile device, We may
            collect certain information automatically, including, but not
            limited to, the type of mobile device You use, Your mobile device
            unique ID, the IP address of Your mobile device, Your mobile
            operating system, the type of mobile Internet browser You use,
            unique device identifiers and other diagnostic data. We may also
            collect information that Your browser sends whenever You visit our
            Service or when You access the Service by or through a mobile
            device.
          </h6>

          <h3>Tracking Technologies and Cookies</h3>
          <h6>
            We use Cookies and similar tracking technologies to track the
            activity on Our Service and store certain information.
            <br />
            Tracking technologies used are beacons, tags, and scripts to collect
            and track information and to improve and analyze Our Service.
            <br />
            You can instruct Your browser to refuse all Cookies or to indicate
            when a Cookie is being sent.
            <br />
            However, if You do not accept Cookies, You may not be able to use
            some parts of our Service.
            <br />
            Cookies can be "Persistent" or "Session" Cookies.
            <br />
            Persistent Cookies remain on your personal computer or mobile device
            when You go offline, while Session Cookies are deleted as soon as
            You close your web browser. Learn more about cookies:{" "}
            <a
              href="https://www.termsfeed.com/blog/cookies/"
              className="privecyPolicy-link"
            >
              All About Cookies.
            </a>
            <br />
            We use both session and persistent Cookies for the purposes set out
            below:
          </h6>
          <ul className="privecyPolicy-list">
            <li>
              Necessary / Essential Cookies Type: Session Cookies Administered
              by: Us <br />
              Purpose: These Cookies are essential to provide You with services
              available through the Website and to enable You to use some of its
              features. <br />
              They help to authenticate users and prevent fraudulent use of user
              accounts.
              <br />
              Without these Cookies, the services that You have asked for cannot
              be provided, and We only use these Cookies to provide You with
              those services.
              <br />
            </li>

            <br />
            <li>
              Cookies Policy / Notice Acceptance Cookies Type:Persistent Cookies
              <br />
              Administered by: Us
              <br />
              Purpose: These Cookies identify if users have accepted the use of
              cookies on the Website.
            </li>

            <br />
            <li>
              Functionality CookiesType: Persistent Cookies
              <br />
              Administered by: Us
              <br />
              Purpose: These Cookies allow us to remember choices You make when
              You use the Website, such as remembering your login details or
              language preference.
              <br />
              The purpose of these Cookies is to provide You with a more
              personal experience and to avoid You having to re-enter your
              preferences every time You use the Website.
              <br />
              For more information about the cookies we use and your choices
              regarding cookies, please visit our Cookies Policy or the Cookies
              section of our Privacy Policy.
            </li>
          </ul>
          <h3>Use of Your Personal Data</h3>
          <h6>The Company may use Personal Data for the following purposes:</h6>
          <ul className="privecyPolicy-list">
            <br />{" "}
            <li>
              To provide and maintain our Service, including to monitor the
              usage of our Service.
            </li>
            <br />{" "}
            <li>
              To manage Your Account: <br />
              to manage Your registration as a user of the Service. The Personal
              Data You provide can give You access to different functionalities
              of the Service that are available to You as a registered user.
            </li>
            <br />{" "}
            <li>
              For the performance of a contract: <br />
              the development, compliance and undertaking of the purchase
              contract for the products, items or services You have purchased or
              of any other contract with Us through the Service.
            </li>
            <br />{" "}
            <li>
              To contact You:
              <br /> To contact You by email, telephone calls, SMS, or other
              equivalent forms of electronic communication, such as a mobile
              application's push notifications regarding updates or informative
              communications related to the functionalities, products or
              contracted services, including the security updates, when
              necessary or reasonable for their implementation.
            </li>
            <br />{" "}
            <li>
              To provide You with news, special offers and general information
              about other goods, services and events which we offer that are
              similar to those that you have already purchased or enquired about
              unless You have opted not to receive such information.
            </li>
            <br />{" "}
            <li>
              To manage Your requests: To attend and manage Your requests to Us.
            </li>
            <br /> <br />
          </ul>
          <h6>
            We may share your personal information in the following situations:
          </h6>
          <ul className="privecyPolicy-list">
            <li>
              With Service Providers:
              <br /> We may share Your personal information with Service
              Providers to monitor and analyze the use of our Service, to
              contact You.
            </li>
            <br />{" "}
            <li>
              For Business transfers:
              <br /> We may share or transfer Your personal information in
              connection with, or during negotiations of, any merger, sale of
              Company assets, financing, or acquisition of all or a portion of
              our business to another company.
            </li>
            <br />{" "}
            <li>
              With Affiliates:
              <br /> We may share Your information with Our affiliates, in which
              case we will require those affiliates to honor this Privacy
              Policy. Affiliates include Our parent company and any other
              subsidiaries, joint venture partners or other companies that We
              control or that are under common control with Us.{" "}
            </li>
            <br />{" "}
            <li>
              With Business partners: <br />
              We may share Your information with Our business partners to offer
              You certain products, services or promotions.
            </li>
            <br />{" "}
            <li>
              With other users: <br />
              when You share personal information or otherwise interact in the
              public areas with other users, such information may be viewed by
              all users and may be publicly distributed outside. If You interact
              with other users or register through a Third-Party Social Media
              Service, Your contacts on the Third-Party Social Media Service may
              see Your name, profile, pictures and description of Your activity.
              Similarly, other users will be able to view descriptions of Your
              activity, communicate with You and view Your profile.
            </li>
          </ul>
          <h3>Retention of Your Personal Data</h3>
          <h6>
            The Company will retain Your Personal Data only for as long as is
            necessary for the purposes set out in this Privacy Policy. We will
            retain and use Your Personal Data to the extent necessary to comply
            with our legal obligations (for example, if we are required to
            retain your data to comply with applicable laws), resolve disputes,
            and enforce our legal agreements and policies. The Company will also
            retain Usage Data for internal analysis purposes. Usage Data is
            generally retained for a shorter period of time, except when this
            data is used to strengthen the security or to improve the
            functionality of Our Service, or We are legally obligated to retain
            this data for longer time periods.
          </h6>
          <h3>Transfer of Your Personal Data</h3>
          <h6>
            Your information, including Personal Data, is processed at the
            Company's operating offices and in any other places where the
            parties involved in the processing are located. It means that this
            information may be transferred to — and maintained on — computers
            located outside of Your state, province, country or other
            governmental jurisdiction where the data protection laws may differ
            than those from Your jurisdiction. Your consent to this Privacy
            Policy followed by Your submission of such information represents
            Your agreement to that transfer. The Company will take all steps
            reasonably necessary to ensure that Your data is treated securely
            and in accordance with this Privacy Policy and no transfer of Your
            Personal Data will take place to an organization or a country unless
            there are adequate controls in place including the security of Your
            data and other personal information.
          </h6>
          <h3>Disclosure of Your Personal Data</h3>
          <h3>Business Transactions</h3>
          <h6>
            If the Company is involved in a merger, acquisition or asset sale,
            Your Personal Data may be transferred. <br />
            We will provide notice before Your Personal Data is transferred and
            becomes subject to a different Privacy Policy.
          </h6>
          <h3>Law enforcement</h3>
          <h6>
            Under certain circumstances, the Company may be required to disclose
            Your Personal Data if required to do so by law or in response to
            valid requests by public authorities (e.g. a court or a government
            agency).
          </h6>
          <h3>Other legal requirements</h3>
          <h6>
            The Company may disclose Your Personal Data in the good faith belief
            that such action is necessary to:
          </h6>
          <ul className="privecyPolicy-list">
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of the Company</li>
            <li>
              Prevent or investigate possible wrongdoing in connection with the
              Service
            </li>
            <li>
              Protect the personal safety of Users of the Service or the public
            </li>
            <li>Protect against legal liability</li>
          </ul>
          <h3>Security of Your Personal Data</h3>
          <h6>
            The security of Your Personal Data is important to Us, but remember
            that no method of transmission over the Internetor method of
            electronic storage is 100% secure. <br />
            While We strive to use commercially acceptable means to protect Your
            Personal Data, We cannot guarantee its absolute security.
          </h6>
          <h3>
            Your California Privacy Rights (California's Shine the Light law)
          </h3>
          <h6>
            Under California Civil Code Section 1798 (California's Shine the
            Light law), California residents with an established business
            relationship with us can request information once a year about
            sharing their Personal Data with third parties for the third
            parties' direct marketing purposes. If you'd like to request more
            information under the California Shine the Light law, and if you are
            a California resident, You can contact Us using the contact
            information provided below.
          </h6>
          <h3>
            California Privacy Rights for Minor Users (California Business and
            Professions Code Section 22581)
          </h3>
          <h6>
            California Business and Professions Code section 22581 allow
            California residents under the age of 18 who are registered users of
            online sites, services or applications to request and obtain removal
            of content or information they have publicly posted. To request
            removal of such data, and if you are a California resident, You can
            contact Us using the contact information provided below, and include
            the email address associated with Your account. Be aware that Your
            request does not guarantee complete or comprehensive removal of
            content or information posted online and that the law may not permit
            or require removal in certain circumstances.
          </h6>
          <h3>Links to Other Websites</h3>
          <h6>
            Our Service may contain links to other websites that are not
            operated by Us. If You click on a third party link, You will be
            directed to that third party's site.
            <br /> We strongly advise You to review the Privacy Policy of every
            site You visit.
            <br />
            We have no control over and assume no responsibility for the
            content, privacy policies or practices of any third party sites or
            services.
          </h6>
          <h3>Changes to this Privacy Policy</h3>
          <h6>
            We may update our Privacy Policy from time to time. We will notify
            You of any changes by posting the new Privacy Policy on this page.
            <br />
            We will let You know via email and/or a prominent notice on Our
            Service, prior to the change becoming effective and update the "Last
            updated" date at the top of this Privacy Policy.
            <br />
            You are advised to review this Privacy Policy periodically for any
            changes. Changes to this Privacy Policy are effective when they are
            posted on this page.
          </h6>
          <h3>Contact Us</h3>
          <h6>
            If you have any questions about this Privacy Policy, You can contact
            us:
          </h6>
          <ul className="privecyPolicy-list">
            <li>By email: Info@biomarkerz.com</li>
            <li>
              By visiting this page on our website:{" "}
              <a
                href="https://www.biomarkerz.com/contact"
                className="privecyPolicy-link"
              >
                https://www.biomarkerz.com
              </a>
            </li>
          </ul>
        </div>
      </div>
      <Footer />
    </React.Fragment>
  );
};

export default PrivacyPolicy;
